M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, April 09, 2023 at 03:37:53 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-09T15:37:53-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.700
%
G90
G05
T1
X163.779Y-76.094
X202.094Y-102.549
X202.109Y-64.434
T0
M30
