M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, April 09, 2023 at 03:37:04 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-09T15:37:04-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.700
%
G90
G05
T1
X119.529Y-58.204
X138.549Y-55.694
X158.049Y-72.264
T0
M30
