M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, April 09, 2023 at 03:47:09 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-09T15:47:09-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X121.032Y-150.818
X165.197Y-113.278
X194.516Y-78.734
T0
M30
